#!/bin/sh

lib=lib
schema=smsgenerate.xsl
classpath=$lib/xalan.jar

if [ ! -f "$schema" ]; then
    echo "ERROR: Schema not found"
    exit 1
fi

rm -f -r java

java_cmd="java -cp $classpath org.apache.xalan.xslt.Process -in application.xml -xsl $schema"

echo $java_cmd

$java_cmd
